In [1]:
import pandas as pd
import preprocessing as prep

## Initialisation

In [2]:
df = pd.read_excel("/home/congo/Bureau/2022-m1-staps/motives_part/data_motives/data_motives_final.xlsx","haller") 
#renommer les lignes ( remplacer 0 par etudiant_0)
df_const =df
nlin,ncol = df.shape
line_name = ['etudiant_' + str(i) for i in range(nlin)]
# print(line_name)
df.index = line_name
df_const.index = line_name
#df

In [3]:
# partie donn√© rejeter dans l'analyse
df_perso =df.iloc[:,:39]
#df_perso

In [4]:
#stoker le nom des colonnes
column_name = [c for c in df]

In [5]:
# transformer boy en 0 et Girl en 1
df['Sexe'] = df['Sexe'].map({'Boy': 0 ,'Girl': 1}, na_action=None)
newdf = df.sort_values(by='Sexe')

In [6]:
# pont entre boy et girl
# print(newdf.loc[495,'Sexe'])
# print(newdf.loc[496,'Sexe'])

In [7]:
df_boy = newdf[:495]
# print(df_boy.loc[495,'Sexe'])
# print(df_boy.shape)

In [8]:
# retour des nom des colonnes
newdf['Sexe'] = newdf['Sexe'].map({0 : 'Boy' ,
                             1 : 'Girl'
                             },
                             na_action=None)

# print(newdf.loc[:,'Sexe'])

In [9]:
df_boy = newdf[:495]
# print(df_boy.loc[495,'Sexe'])
# print(df_boy.shape)

In [12]:
df_qualif_boy =pd.read_csv("/home/congo/Bureau/2022-m1-staps/motives_part/data_motives/clustering_boy.csv")
df_qualif_boy

,Unnamed: 0,Confort,Securite,Qualite,Force,Maintien,Puissance,Competition,Muscle,Beaute,...,Sexy,Plaisir,Groupe,Partage,Role,Performance,Meilleur,Individualiste,detente,clust
0,0,0.140228,0.137599,0.120947,0.050248,0.200409,0.305288,0.353491,0.035933,0.150453,...,0.131756,0.049664,0.784984,0.270231,0.153959,0.026293,0.237803,0.059305,0.192229,1
1,1,0.259847,0.063786,0.004703,0.020282,-0.101705,0.020282,0.185773,0.029394,0.034098,...,-0.278954,0.813639,0.098471,0.063198,-0.558789,0.573192,0.059377,-0.323045,0.215755,2
2,2,0.075472,0.043409,0.050007,0.035361,0.041166,0.045784,0.071250,0.069402,0.248714,...,0.058451,0.035361,0.073493,0.023750,0.024541,0.034965,0.033118,0.035097,0.023882,1
3,3,0.082066,0.366603,0.101077,0.120089,0.360583,0.072560,0.085868,0.176489,0.000000,...,0.525032,0.706274,0.397338,0.102662,0.116603,0.082383,0.047845,0.202155,0.065272,1
4,4,0.953540,0.047065,0.025557,0.000000,0.313533,0.010521,0.082212,0.002886,0.550952,...,0.042316,0.015409,0.029747,0.016154,0.012011,0.046041,0.030120,0.056655,0.007029,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,557,0.024623,0.040360,0.054487,0.071784,-0.086928,0.097541,0.000000,0.000000,0.160512,...,0.000000,0.901309,0.913833,0.925640,-0.943719,0.954772,0.000000,-0.992629,1.000000,3
558,558,0.182209,0.166667,0.341224,0.162841,0.298661,0.170493,0.109995,0.072453,0.127929,...,0.608800,0.375897,0.203491,0.126255,0.088953,0.163080,0.120277,0.100670,0.073649,1
559,559,0.000000,0.021602,0.067057,0.086409,0.197120,0.050855,0.087309,0.197120,0.372187,...,0.321332,0.124212,0.359136,0.378938,0.319532,0.335284,0.168317,0.590459,0.423042,2
560,560,0.282977,0.279784,0.296487,0.334562,0.279538,0.665438,0.295996,-0.411447,0.000000,...,-0.635962,0.359371,0.301400,0.384672,0.352248,0.211005,-0.398674,0.000000,0.000000,2
561,561,0.072732,0.065028,0.079676,0.098327,0.029093,0.032083,0.030411,0.019767,0.034415,...,0.079372,0.206386,0.169235,0.004866,0.031171,0.010998,0.035884,0.025494,0.024582,1

In [13]:
#                             Boy part
# donn√©e qualif et cluster 
df_qualif_boy =pd.read_csv("/home/congo/Bureau/2022-m1-staps/motives_part/data_motives/clustering_boy.csv")
df_qualif_boy.index = df_qualif_boy.iloc[:,0]

df_qualif_boy = df_qualif_boy.iloc[:,:73]

df_qualif_boy = df_qualif_boy.iloc[:,1:]
df_qualif_boy.rename(columns = {'clust':'profil'})

with pd.ExcelWriter("df_qualif_boy.xlsx") as writer:
   df_qualif_boy.to_excel(writer, freeze_panes=(1,1))
#df_qualif_boy

# concater les donn√©es perso et qualificatif
df_final = pd.concat([df_perso,df_qualif_boy] , axis= 1)
with pd.ExcelWriter("/home/congo/Bureau/2022-m1-staps/motives_part/data_motives/final_boy.xlsx") as writer:
   df_final.to_excel(writer, freeze_panes=(1,1))
#df_final

## Preprocessing

In [23]:
# prepocessing only with boy 
data = prep.imputation(df_boy)

data_clean , data_correct = prep.preprocessing(data)

data_ready = prep.Normalisation(data)
#print(data_ready)

## Transfert of data python to Rstudio for clustering

In [25]:
def transfert (data_ready,column_name,file_name):
    # mettre data en df
    df = pd.DataFrame(data_ready)


    df_const = df.astype(float,errors='raise')
    # renommer les colonne
    df.columns = column_name[39:]
    df_const.columns = column_name[39:]
    #print(df.shape)

    # 'Confiance en soi' par 'Confiance_en_soi'
    # print(column_name[90])
    column_name[90] = 'Confiance_en_soi'
    # print(column_name[90])
    df = df.rename(columns={'Confiance en soi':'Confiance_en_soi'}) 

    # print(df['Confiance_en_soi'])
    # df_cluster.info()
    # probleme de type alors on le change
    df = df.astype(float,errors='raise')
    # df_cluster.info()    
    

    # with pd.ExcelWriter(file_name) as writer:
    #   df.to_excel(writer, freeze_panes=(1,1))

    df.to_csv(file_name)

In [28]:

column_name = column_name
file_name = '/home/congo/Bureau/2022-m1-staps/motives_part/data_motives/boy.csv'
transfert(data_ready,column_name,file_name)